language: go

go:
  - 1.6

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get gopkg.in/yaml.v2
  - chmod +x coverage.sh

script:
  - ./coverage.sh

after_success:
  - $HOME/gopath/bin/goveralls -coverprofile=full_coverage.out 